openapi: 3.0.0

info:
  title: Invoice System Quote Management API
  version: 1.0.0
  description: |
    API for managing Quote API

servers:
  - url: http://localhost:8080
    description: Local Server

tags:
  - name: Quote
    description: Endpoints for managing Quote

paths:
  /customer/{customerId}/quotes:
    post:
      summary: Create a new quote for customer
      tags:
        - Quote
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewQuote'
            example:
              quoteDate: "2000-01-01"
              validUntil: "2000-01-01"
              items:
                - itemName: "item name"
                  description: "item description"
                  quantity: 10
                  rate: 100
                  hsnCode: "12345678"
                  taxPercent: 18
              currency: "INR"
      responses:
        '201':
          description: Quote created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'

    get:
      summary: Get all quote with customer
      tags:
        - Quote
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of quote
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'

  /customer/{customerId}/quotes/{quoteId}:
    get:
      summary: Get quote by ID for customer
      tags:
        - Quote
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
        - name: quoteId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Quote found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Quote not found

    put:
      summary: Update item for quote by ID for customer with Id
      tags:
        - Quote
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
        - name: quoteId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewQuote'
            example:
              quoteDate: "2000-01-01"
              validUntil: "2000-01-01"
              items:
                - itemName: "item name"
                  description: "item description"
                  quantity: 10
                  rate: 100
                  hsnCode: "12345678"
                  taxPercent: 18
      responses:
        '200':
          description: Quote update successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
    delete:
      summary: Delete item for quote by ID for customer with Id
      tags:
        - Quote
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
        - name: quoteId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Quote by ID for customer with Id successfully delete
        '404':
          description: Quote not found


components:
  schemas:
    Quote:
      type: object
      required:
        - id
        - quoteNumber
        - quoteDate
        - validUntil
        - subTotal
        - taxAmount
        - status
        - currency
        - items
      properties:
        id:
          type: integer
          format: int64
          example: 1
        quoteNumber:
          type: string
          example: "Q-2025:001"
        quoteDate:
          type: string
          format: date
          example: "2000-01-01"
        validUntil:
          type: string
          format: date
          example: "2000-01-01"
        subTotal:
          type: number
          format: double
          example: 1180.0
        taxAmount:
          type: number
          format: double
          example: 180.0
        status:
          type: string
          enum: [ DRAFT, APPROVED, SENT, ACCEPTED, REJECTED ]
          example: "DRAFT"
        currency:
          type: string
          example: "INR"

        items:
          type: array
          items:
            $ref: '#/components/schemas/QuoteItemResponse'

    QuoteItemResponse:
      type: object
      required:
        - id
        - itemName
        - description
        - quantity
        - rate
        - hsnCode
        - taxPercent
        - total
      properties:
        id:
          type: integer
          format: int64
          example: 1
        itemName:
          type: string
          example: "item name"
        description:
          type: string
          example: "item description"
        quantity:
          type: integer
          format: int32
          example: 10
        rate:
          type: number
          format: double
          example: 100.0
        hsnCode:
          type: string
          example: "12345678"
        taxPercent:
          type: number
          format: double
          example: 18.0
        total:
          type: number
          format: double
          example: 1180.0

    NewQuote:
      type: object
      properties:
        quoteDate:
          type: string
          format: date
          example: "2025-04-16"
        validUntil:
          type: string
          format: date
          example: "2025-04-16"
        currency:
          type: string
          example: "INR"
        items:
          type: array
          items:
            $ref: '#/components/schemas/QuoteItem'
      required:
        - quoteDate
        - validUntil
        - currency
        - items
    QuoteItem:
      type: object
      required:
        - itemName
        - description
        - quantity
        - rate
        - hsnCode
        - taxPercent
      properties:
        itemName:
          type: string
          example: "item name"
        description:
          type: string
          example: "item description"
        quantity:
          type: integer
          format: int32
          example: 10
        rate:
          type: integer
          format: int32
          example: 1000
        hsnCode:
          type: string
          example: "12345678"
        taxPercent:
          type: number
          format: float
          example: 18